bcoe/c8

.travis.yml, package-lock.json, package.json
Windows tests should now work due to landing:
https://github.com/istanbuljs/v8-to-istanbul/pull/11
=> chore: enable windows tests

bin/c8.js
=> fix: we were not exiting with 1 if mkdir failed

lib/parse-args.js, lib/report.js, package-lock.json, package.json, test/integration.js
=> chore: update deps to address warning in cross-spawn

package-lock.json, package.json
this cropped up when users were using proxyquire, see:
https://github.com/googleapis/nodejs-error-reporting/pull/389
=> fix(deps): merging failed when the same script occurred multiple times

index.d.ts, index.js, package.json
=> feat: adds TypeScript definitions

package-lock.json, package.json
there was a bug identified in [v8-to-istanbul](https://github.com/istanbuljs/v8-to-istanbul/pull/89) which was causing a crasher in c8.
=> fix(deps): update to v8-to-istanbul with fix for crasher

lib/parse-args.js
=> fix: add missing space in text

package-lock.json, package.json
=> chore(deps): fix audit warnings

README.md
Native V8 coverage is now supported in all active release lines.
=> docs: remove "bleeding edge Node.js features" wording

.github/publish.yml, .github/release-please.yml, .github/workflows/ci.yaml, .github/workflows/release-please.yml
* switch to action for releases.
* make it so adding `ci` label kicks off build.
=> build: switch to release-please action

lib/parse-args.js, lib/report.js, package-lock.json, package.json, test/integration.js, test/integration.js_10.snap
Upgrade to latest version of standard linter.
=> build(deps): update standard linter

package-lock.json, package.json
See: https://github.com/istanbuljs/v8-to-istanbul/pull/146
=> fix(deps): v8-to-istanbul with fix for Windows paths

.github/workflows/ci.yaml
Tests are passing on my machine:
**Version**: `v17.3.0`
**Platform**: `Linux 5.15.12-arch1-1 #1 SMP PREEMPT Wed, 29 Dec 2021 12:04:56 +0000 x86_64 GNU/Linux`
=> build: Add Node 17 to matrix

.github/workflows/ci.yaml, .github/workflows/release-please.yml
* update to actions/checkout@v2
* update to actions/setup-node@v2
* switch to Node.js 16 for publishing and Windows/Coverage workflows
* add `workflow_dispatch`
* add `fail-fast: false`
* switch to `npm ci`
* use caching
=> build: update GitHub action configuration

CONTRIBUTING.md, MAINTAINERS_GUIDE.md, README.md
=> docs: md formatting changes

.nycrc, index.d.ts
=> chore: fix indentation

.github/workflows/ci.yaml, .github/workflows/release-please.yml
=> fix: update actions/setup-node and actions/setup-node to v3

package-lock.json, package.json, test/integration.js.snap, test/integration.js_10.snap
=> fix(deps): update deps to latest

.github/workflows/release-please.yml
---
Noticed this on my fork. It created a PR when I merged the upstream patches and since I have actions enabled there.
=> chore(ci): skip release please on forks

package.json
LICENSE.txt is already included by default
=> chore: remove non-existent file from package.json

index.d.ts
This updates the `Report` options in index.d.ts with the options `skipFull` and `excludeNodeModules`.
Fixes #382
=> feat: add `skipFull` and `excludeNodeModules` to type definitions

index.d.ts
Adds typings for `reporterOptions` implemented in #423. Demo at [TS Playground](https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgPIAczAPYgM7IDeAUMslBOtlJFBlrngPwBcyAShAtQCYA8eMFFABzADQcuvAUNESAriADWIbAHcQAPk3EAvsWIQAHlRrJu+MOdwxgItvRz5kAXiKlylarUeM2JMjJIIzB-ZDwlYHQAMXkAGzi2IXkICQBbOCMAYWw4vDYARgAmAAZkXTEDQOQACzA0xPdqsjjQJQBZOHR0aH8PZuQRCDAABTgwGoAKAEpCTzB5KBBkAvLKgbIKOPHgADcIMYmZuYoFpeQAIjgLtf7muDw8YcOp2fnF5cJdW4H9aoq7nc4txdv4AXcAPQQ5AAATAeAAtMYeggwEioFBqMgEQjkKorJxuFAeHcAFZ4XBsC4AOghtjiEGp5NwF3W5T0QA).
These typings are not 100% exact, as `reporter` is neither strictly typed to known values only. 
Typings could be improved by utilizing the `@types/istanbul-reporters` package if wanted:
```ts
import type { ReportOptions } from 'istanbul-reports'
export interface Options { …
```
=> feat: add typings for reporterOptions

package-lock.json
Update pacakge-lock.json to address audit issues.
=> deps: update package-lock

.github/workflows/ci.yaml, bin/c8.js, package-lock.json, package.json, test/integration.js
- [ x] `npm test`, tests passing
- [ x] `npm run test:snap` (to update the snapshot)
Closes #506
=> chore(deps): Remove rimraf

.github/workflows/release-please.yml, test/integration.js, test/integration.js.snap
test: fix snapshot
build: update release-please to latest
test: fix module name checked for
=> test: fix snapshot

CONTRIBUTING.md
=> doc(CONTRIBUTING): remove dead link, update broken link

.github/workflows/ci.yaml, package-lock.json, package.json
Update to version of bcoe/v8-coverage that addresses #543
=> fix(deps): update bcoe/v8-coverage addressing v8 issue
