bin/c8.js
lib/spawn.js
package.json

allow inspector to pick a default port and, rather than polling for port, wait until port # is output to `stderr` 
I think if we were to add a standardized prefix to debugger output in Node.js, we could easily strip any messages generated by the debugger, while still kicking along other messages to `stderr` (refs: https://github.com/nodejs/node/issues/17337).
---
@TimothyGu, I assume that this message isn't output until the port is taking connections?
reviewer: @TimothyGu

feat: switch to stderr and default port

---

bin/c8.js

Fixes the symptoms documented at https://github.com/nodejs/node/issues/17336. This commit contains multiple parts that are hard to separate into separate commits/PRs, but I've documented the bits that I changed below:
- Use `process.execPath` instead of hardcoding `'node'`
- Make sure to call `done()` in the `foreground()` callback; doing this used to segfault for unknown reasons (presumably inside V8), but will no longer do so after the timing fixes in this PR
- Listen for Inspector events before enabling Profiler/Runtime/Debugger, since events will start flowing in as soon as those are enabled
- Attempt to enable Profiler/Runtime/Debugger before runIfWaitingForDebugger, but do not expect them to complete before runIfWaitingForDebugger finishes
- Wait for the initial pause brought about …

Fix event timing

---

README.md

@demurgos and I have been having long conversations about implementation details surrounding c8, and I think part of the problem was that I've done a poor job of describing the goals I have in mind (they lived only in my head, which isn't useful).
tldr; I'd like this project to demonstrate a powerful code coverage solution relying primarily on native V8 functionality, and minimal user-land modules.
_data-transformations are okay, but I don't want to parse JavaScript with Babel, muck with Node's runtime, etc._

docs: add clarification about goals of this project

---

.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
MAINTAINERS_GUIDE.md
README.md

- issue template
- PR template
- contributing guide
- maintainers guide
closes #35

chore(maintenance): add project guides

---

lib/commands/check-coverage.js
lib/commands/report.js
lib/parse-args.js
lib/report.js
test/integration.js.snap

Add new option `--reports-dir` for customization of the reports output. 
Tests notice: as this new option is bypassed directly to reporter framework, I think that testing of different outputting should be already tested there. Maybe you have other opinion?
Thank u for the attention

Proposition for fixing Issue #64

---

bin/c8.js

feat: force exit the process when completed

---

lib/is-cjs-esm-bridge.js
lib/report.js
test/fixtures/export.cjs
test/fixtures/import.mjs
test/integration.js.snap

Fixes https://github.com/bcoe/c8/issues/14, by excluding results that contains coverage of [the CJS-ESM bridge](https://github.com/nodejs/node/blob/v12.0.0/lib/internal/modules/esm/create_dynamic_module.js#L12-L20).
main.mjs:
```js
import lib from './lib.cjs';
lib();
``` 
lib.cjs:
```js
module.exports = () => 'Hi';
``` 
```console
$ node bin/c8.js node --experimental-modules main.mjs
----------|----------|----------|----------|----------|-------------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
----------|----------|----------|----------|----------|-------------------|
All files |      100 |      100 |        0 |      100 |                   |
lib.cjs  |      100 |      100 |        0 |      100 |                   |
main.mjs |      100 |      100 | …
```

fix: exclude coverage of the CJS-ESM bridge from results

---

bin/c8.js
test/integration.js

Currently, when `c8` fails to create coverage reports because of, for example, unknown report type `--reporter=unknown`, it causes the following two problems:
__1__. The error is displayed as an `UnhandledPromiseRejectionWarning` to end users.
```console
$ c8 --reporter=unknown echo ""
(node:26891) UnhandledPromiseRejectionWarning: Error: Cannot find module 'unknown'
Require stack:
- /Users/shinnn/c8/node_modules/istanbul-reports/index.js
- /Users/shinnn/c8/lib/report.js
- /Users/shinnn/c8/lib/commands/check-coverage.js
- /Users/shinnn/c8/lib/commands/report.js
- /Users/shinnn/c8/bin/c8.js
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:610:15)
at Function.Module._load (internal/modules/cjs/loader.js:526:27)
at Module.require (internal/modules/cjs/loader.js:666:19)
at …
```

fix: exit with code 1 when report output fails

---

bin/c8.js
package-lock.json
package.json
test/fixtures/disable-fs-promises.js
test/legacy-node.js

https://github.com/bcoe/c8/commit/206b83f156ff93d1a7b211d61bd4fd8e9a4cd95f introduced the `mkdirp` dependency to `c8`, but I'm very opposed to use such a no longer maintained package.
For feature detection, we can check the existence of [`fs.promises`](https://nodejs.org/dist/latest-v12.x/docs/api/fs.html#fs_fs_promises_api) which is only available in Node.js >= 10.0.0.

fix: remove the unmaintained mkdirp dependency

---

lib/parse-args.js

To simplify migrating from `nyc` to `c8`, support loading `.nycrc`.

feat: load .nycrc/.nycrc.json to simplify migration

---

lib/parse-args.js

BREAKING CHANGE: temp directory now defaults to setting for report directory

feat!: default temp directory to report directory

---

lib/parse-args.js

temporary files were being placed in top-level `coverage` folder.

fix: temporary files should be in tmp folder

---

package-lock.json
package.json

This pulls in a fix to v8-to-istanbul that addresses the bug reported by @oliversalzburg.
CC: @shinnn, I used your patch.

fix: HTML report now has correct source positions for Node >10.16.0

---

lib/commands/check-coverage.js
test/integration.js
test/integration.js.snap

Fixes: https://github.com/bcoe/c8/issues/187
When implementing all I neglected to supply it when building
`Report` in the `check-coverage.js` command. This commit
rectifies that and adds two test cases for `check-coverage`
as a flag and command used in conjunction with `--all` to
prevent regression.
- [ x ] `npm test`, tests passing
- [ x ] `npm run test:snap` (to update the snapshot)
- [ x ] tests and/or benchmarks are included

fix: All flag not propagated to check-coverage command

---

lib/report.js
test/fixtures/source-maps/fake-source-map.js
test/integration.js
test/integration.js.snap
test/integration.js_10.snap

Fixes: #232 
Refs: https://github.com/nodejs/node/pull/34305

fix: ignore missing source maps in raw coverage output

---

.nycrc
lib/report.js
test/integration.js.snap
test/integration.js_10.snap

Refs: https://github.com/nodejs/node/pull/35498, https://github.com/nodejs/node/issues/35646

fix: support node@v15.x.x built-in modules

---

lib/report.js
test/integration.js
test/integration.js_10.snap

These warnings were creating a lot of confusion for when running coverage on the Node.js project.
Rather than always outputting warnings, let's allow people to opt into seeing warnings if they set `NODE_DEBUG=c8`.

feat: use debuglog rather than console.warn

---

lib/commands/report.js
lib/parse-args.js
lib/report.js
test/integration.js_10.snap

Added ability to `--skip-full` (#286)

add --skip-full

---

lib/commands/report.js
lib/parse-args.js
lib/report.js
test/integration.js
test/integration.js.snap
test/integration.js_10.snap

Allow exclude logic to be passed to v8-to-istanbul, such that it is applied after
source maps.
Fixes #224
---
@robpalme I needed this functionality for 1:many source maps, from bundlers like rollup:
```
yargs/node_modules/tslib |   98.17 |       50 |     100 |   98.17 |                                
tslib.es6.js            |   98.17 |       50 |     100 |   98.17 | 207-208,214-215  
```
This may take some additional tweaking in follow on PRs to match your exact use case, but I believe it's a start.

feat: introduce --exclude-after-remap flag

---

index.d.ts

I started out to add the new `excludeAfterRemap` option (which is a helpful and extremely timely addition!). While I was in there, I tweaked a few other types to hopefully make them more accurate.

Update Report option types

---

lib/report.js
package-lock.json
package.json
test/integration.js_10.snap

Fixes #300 with the fix outline in the issue.
As mentioned in the issue, fixing it reveals an upstream bug that causes test to fail. I have verified that on both node v14.16.1 and v16.0.0:
- Tests pass on Linux (docker)
- Locally linking to a fixed version of `v8-to-istanbul` makes tests pass on Windows

fix: address bugs with source remapping on Windows

---

README.md
lib/parse-args.js
test/fixtures/config/.c8rc.json
test/integration.js_10.snap
test/parse-args.js

feat: add --config option and documentation on options and configs

---

lib/commands/report.js
lib/parse-args.js
lib/report.js
test/integration.js_10.snap

Hello,
It's basically a trivial port of the --exclude-node-modules option from nyc.
Cheers,
Sergiy

feat: add --exclude-node-modules option

---

README.md
lib/commands/check-coverage.js
lib/commands/report.js
lib/parse-args.js
test/integration.js
test/integration.js.snap
test/integration.js_10.snap

feat: `--100`

---

README.md
index.d.ts
lib/commands/check-coverage.js
lib/commands/report.js
lib/parse-args.js
lib/report.js
package-lock.json
test/fixtures/custom-ext.special
test/integration.js
test/integration.js.snap
test/integration.js_10.snap

Adds the `extension` option from nyc.
I've setup the CLI to support the same arguments as nyc (which translates to the config file also).
Currently without this change there is no way to use c8 with require hooks for tools without the default extensions (https://github.com/istanbuljs/schema/blob/master/default-extension.js). For example using a Marko, Svelte, Vue, etc require hook will not work.
With this PR you can currently set it to `false` to disable this extension check, same as nyc. It may make sense to use different defaults than nyc here, and just allow any extension. I've currently opted to just keep a similar api to nyc.

feat: add --extension option

---

README.md

Somehow GitHub's markdown requires escaping `|` inside back-ticks.

docs: Correctly display `--extension` row in cli options table

---

package-lock.json
package.json

Currently there is no custom `tsconfig.json` to be used by `ts-node` inside this project. There is no reason to let `ts-node` resolve a configuration present outside this project on the filesystem. Fixes #348.

fix(ts-node): Disable tsconfig.json loading

---

.gitattributes

On Windows `autocrlf` is `true` by default so this enforces LF regardless of the git settings.

chore: enforce LF

---

package.json

test: package.json `test:snap` script to use cross-env

---

package.json

I was hitting the timeout on WSL. 10s fixes the issue for me.

chore: increase mocha timeout to 10s

---

test/integration.js.snap

I suspect this is due to a bug in chai-jest-snapshot.

chore: regenerate test/integration.js.snap

---

lib/report.js
test/integration.js_10.snap

This PR drastically improves performance for large codebases.
Below is the result of total time collecting coverage for [my project](https://github.com/traPtitech/traQ_S-UI) which uses c8 internally in vitest.
|    |Before|After|Diff|
|---|---|---|---|
|with `all=false`|37.056s|7.126s|-29.93s (-80%)|
|with `all=true`|33.515s|2.849s|-30.66s (-91%)|
This result was measured by adding `console.time` and `console.timeEnd` around here.
https://github.com/bcoe/c8/blob/ae1f5e599476ae38b09b92c9f7db837e79cd1693/lib/report.js#L66-L78
This is a bit off topic but FYI [this `this.exclude.globSync(workingDir)` call](https://github.com/bcoe/c8/blob/ae1f5e599476ae38b09b92c9f7db837e79cd1693/lib/report.js#L193) takes 3.6s totally.
So there is a room to improve more if I can change implementation inside …

fix(perf): cache `this.exclude.shouldInstrument` for improved performance

---

lib/report.js

Hi,
this PR is changing the default `maxCols` width from `100` to whatever is the current terminal, using `process.stdout.columns`. If that's not available for any reason(ci?) it fallbacks to 100.

feat: use process.stdout.columns for reporter maxCols

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md

Rename the c8 repo 'master' branch to 'main' in git commands and in a link in the PR template.
I stumbled on the outdated git commands while working on another PR.

docs: change 'master' to 'main' in git commands and links

---

lib/report.js
package-lock.json
test/integration.js.snap
test/integration.js_10.snap

For example:
```
{
reporter: ['text'],
reporterOptions: {
text: { file: 'coverage.txt' },
}
}
```
This enables overriding the `file` option which normally defaults to `null`, so text reporters can write to a file rather than stdout: https://github.com/istanbuljs/istanbuljs/blob/fb8cb4bb99c9e5d36c8b011338d2ab5d3c72ff9c/packages/istanbul-reports/lib/text/index.js#L233-L237

feat: support passing reporter options

---

README.md

While rewriting `vitest`'s coverage configuration documentation I noticed the `per-file` option is not included in `c8`'s documentation. It is implemented though:
https://github.com/bcoe/c8/blob/bc347a91f06a3fea7b7425c4affd66d7f8b9d416/lib/commands/check-coverage.js#L46-L52

docs: add `--per-file`

---

lib/commands/report.js
test/integration.js.snap

I saw that the reporter allowed passing reporter options – since #423.
This PR originally also include a use case: c8 config.
```json5
{
reporter: ['text'],
reporterOptions: {
text: { file: 'coverage.txt' },
}
}
```
Here is another real world use case: 
```json
{
"all": true,
"reporter": ["text-summary", "clover", "html"],
"reporterOptions": {
"clover": {"file": "coverage.clover.xml"},
"html": {"subdir": "coverage.html"}
},
"reports-dir": "./reports",
"temp-directory": "./.c8.cache"
}
```
Unfortunately, the original feature forgot to implement the solution to the exact use case.
SO the actual feature was never accessible/working/existing.
Here is the solution: `reporterOptions` from the config are passed to reporters.
I do not have any idea how the CLI could look like to configure this. …

feat: support passing reporter options from config

---

test/parse-args.js

Artifact Directory Unit Tests
test: relative directories for tmpDir and reportsDir
test: absolute directories for tmpDir and reportsDir
1. [x] Make sure you have installed the latest version of Node.js
2. [x] Fork this project on GitHub and clone your fork locally
3. [x] Create local branches to work within. These should also be created directly from the main branch.  Local Fork [here.](https://github.com/mcknasty/c8)
4. [x] Make your changes.
5. [x] Run tests to make sure all is okay (everything should pass except the snapshot).
1. A [complete log](https://gist.github.com/mcknasty/313be9529ebaa41cba7be7e94b8aee09#file-initial-test-txt) of initial test results.
2. As instructed, ignore snapshot failures. [2 failing](https://gist.github.com/mcknasty/313be9529ebaa41cba7be7e94b8aee09#file-ini …

test: additional tests for relative path support

---

.github/workflows/ci.yaml
package-lock.json
package.json

BREAKING CHANGE: Node 18 is now the minimum supported Node.js version
Fixes #529

fix(deps)!: update test-exclude with new glob / minimatch

---

README.md
lib/report.js
package-lock.json
package.json
test/integration.js.snap

Since npm@7 peerDependencies installs deps. Move to the approach used by [pixijs](https://github.com/pixijs/pixijs/pull/8630).

fix: stop installing monocart-coverage-reports

---

package-lock.json
package.json

I noticed in https://github.com/bcoe/c8/commit/13979a76b5b44fc6758f350bae4cb3febd60d75e that you fixed it being a "required" peer dep by not declaring it at all.
Package managers like `pnpm` (or others) may use a stricter `node_modules` layout which would prevent `c8` from accessing `monocart-coverage-reports` because it's not a declared dependency.
Instead of not declaring the dep, you can still use a peer dep but just mark it optional. Users installing `c8` will not get `monocart-coverage-reports` automatically, which I believe is what you intended. But, installing it later will ensure that it's correctly linked.
As an example, see https://github.com/microsoft/TypeChat/blob/ce83b7f63f19786106f82a37ca154bbb579d960b/typescript/package.json#L43-L54, which declares deps on libraries that …

Make monocart-coverage-reports an optional peer dep

---

.editorconfig

when creating my last PR, my editor stripped all trailing whitespace on all lines from the updated snapshot file. Changing `.editorconfig` fixed that

chore: .editorconfig to avoid unintended mods to .snap files
